stages:
  - build

include:
  - project: 'components/package'
    file: '/templates/signing/signing.gitlab-ci.yml'

build_and_sign:
  variables:
    IMAGE_TAG: $CI_COMMIT_REF_SLUG-$CI_COMMIT_SHORT_SHA
